modLoader="javafml"
loaderVersion="[47,)"
license="CC-NC"

[[mods]]
modId="technomagic"
version="0.1.0"
displayName="TechnoMagic"
displayURL="https://www.mcmod.cn/class/11187.html"
credits="Created using mod maker VSCode - https://code.visualstudio.com/"
authors="0825"
description="A Mod."